[package]
name    = "esp-alloc"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"

[target.'cfg(target_arch = "riscv32")'.dependencies]
critical-section = "0.2.7"

[target.xtensa-esp32-none-elf.dependencies]
critical-section = { version = "0.2.7", features = ["custom-impl"]}
xtensa-lx        = { version = "0.7",   features = ["esp32"] }
xtensa-lx-rt     = { version = "0.12",  features = ["esp32"] }
