[package]
name    = "esp-alloc"
version = "0.1.0"
edition = "2021"

[dependencies]
bare-metal = "1.0.0"
log        = "0.4.17"

[dependencies.linked_list_allocator]
version          = "0.9.1"
default-features = false
features         = ["const_mut_refs"]

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv = "0.8.0"

[target.xtensa-esp32-none-elf.dependencies]
xtensa-lx = { version = "0.7.0",  features = ["esp32"] }
