[package]
name    = "esp-alloc"
version = "0.1.0"
edition = "2021"

[dependencies]
bare-metal = "1.0.0"

[target.'cfg(target_arch = "riscv32")'.dependencies]
linked_list_allocator = { version = "0.9.1", default-features = false, features = ["const_mut_refs"] }
riscv                 = "0.8.0"

[target.xtensa-esp32-none-elf.dependencies]
linked_list_allocator = "0.9.1"
xtensa-lx             = { version = "0.7.0",  features = ["esp32"] }

[target.xtensa-esp32s2-none-elf.dependencies]
linked_list_allocator = { version = "0.9.1", default-features = false, features = ["const_mut_refs"] }
xtensa-lx             = { version = "0.7.0",  features = ["esp32s2"] }

[target.xtensa-esp32s3-none-elf.dependencies]
linked_list_allocator = "0.9.1"
xtensa-lx             = { version = "0.7.0",  features = ["esp32s3"] }
